# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7354996c0edb6e27e26e30e2f01e531f9d3260d41a1b49bb187ae464db9fb2331274d37d98e3631fd26790e0fc9555e8a3b642a77d325c5da958e4edfaef672

test:
  secret_key_base: 0f9dd3924f4ba003c66e79f8fdfb694885a71e8c7123a44e2fdfa922b329e9f26fa4f6bc1abda5cdd08cebbccd57539fcd5e06c3e134be27b65e9bf2dffd5003

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
